# ================================
# Base Image with system deps
# ================================
FROM node:22-slim

# Install system dependencies (rarely change)
RUN apt-get update && apt-get install -y --no-install-recommends \
    libpixman-1-0 \
    libcairo2 \
    libpango1.0-0 \
    libjpeg62-turbo \
    libgif7 \
    librsvg2-2 \
  && rm -rf /var/lib/apt/lists/* \
  && apt-get clean

# Set working directory
WORKDIR /usr/src/app
