export enum AllowedFileType {
  PNG = 'png',
  JPG = 'jpg',
  JPEG = 'jpeg',
  PDF = 'pdf',
  DOCX = 'docx',
  XLSX = 'xlsx',
  MP4 = 'mp4',
  MP3 = 'mp3',
  GIF = 'gif',
  ZIP = 'zip',
  RAR = 'rar',
  TXT = 'txt',
  CSV = 'csv',
  HTML = 'html',
  XML = 'xml',
  JSON = 'json',
  SVG = 'svg',
  BMP = 'bmp',
  WEBP = 'webp',
  PPTX = 'pptx',
  M4A = 'm4a',
  DOC = 'doc',
}
